####################################################
# Docker Image List
####################################################
## BITNAMI_SPARK Image
## https://hub.docker.com/r/bitnami/spark

## PYSPARK_JUPYTER_NOTEBOOK
## https://hub.docker.com/r/jupyter/pyspark-notebook

x-spark-common:
  &spark-common
  image: ${BITNAMI_SPARK:-docker.io/bitnami/spark}:${SPARK_VERSION:-3.5.0}
  environment:
    &spark-common-env
    SPARK_USER: spark
    SPARK_PUBLIC_DNS: localhost
    SPARK_DRIVER_HOST: jupyter
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 1G
  volumes:
    - ${JARS_DIR:-./jars}/:/opt/spark/jars

services:
  jupyter:
    image: ${PYSPARK_JUPYTER_NOTEBOOK:-jupyter/pyspark-notebook}:${SPARK_VERSION:-spark-3.5.0}
    container_name: jupyter-notebook
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./jupyter:/home/jovyan/work
      - ${JARS_DIR:-./jars}/:/opt/spark/jars
    environment:
      JUPYTER_ENABLE_LAB: yes
      GRANT_SUDO: yes
    user: root
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

  mysql:
    image: ${MYSQL:-mysql}:${MYSQL_VERSION:-8.0.37}
    container_name: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped

  spark-master:
    <<: *spark-common
    image: ${BITNAMI_SPARK:-docker.io/bitnami/spark}:${SPARK_VERSION:-3.5.0}
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      <<: *spark-common-env
      SPARK_MODE: master

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    ports:
      - 8081:8081
    environment:
      <<: *spark-common-env
      SPARK_MODE: worker
      SPARK_WORKER_WEBUI_PORT: 8081

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    ports:
      - 8082:8082
    environment:
      <<: *spark-common-env
      SPARK_MODE: worker
      SPARK_WORKER_WEBUI_PORT: 8082

  spark-worker-3:
    <<: *spark-common
    container_name: spark-worker-3
    ports:
      - 8083:8083
    environment:
      <<: *spark-common-env
      SPARK_MODE: worker
      SPARK_WORKER_WEBUI_PORT: 8083

volumes:
  juyter_volumns:

networks:
  fashion_campus_networks: